# Generated by Django 3.2.8 on 2021-11-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Menu_name', models.CharField(max_length=100)),
                ('Menu_href', models.CharField(max_length=100)),
                ('Menu_is_active', models.CharField(max_length=100)),
                ('Menu_type', models.CharField(blank=True, max_length=100)),
                ('Created_by', models.CharField(default='Admin', max_length=100)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('Last_modefied', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
