# Generated by Django 3.2.8 on 2021-11-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Parent_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
