# Generated by Django 3.2.8 on 2021-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_menu_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Menu_order',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
