# Generated by Django 3.2.8 on 2021-11-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_menu_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Menu_type',
        ),
        migrations.AddField(
            model_name='menu',
            name='Menu_icon',
            field=models.CharField(default='fa-circle', max_length=100),
        ),
    ]
