# Generated by Django 3.2.8 on 2021-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_auto_20211123_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Menu_type',
            field=models.CharField(default='single', max_length=100),
        ),
    ]
