<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["settings", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create settings</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="settings/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldCategory" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["category", "size" => 30, "class" => "form-control", "id" => "fieldCategory"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSkey" class="col-sm-2 control-label">Skey</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["skey", "size" => 30, "class" => "form-control", "id" => "fieldSkey"]); ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSvalue" class="col-sm-2 control-label">Svalue</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["svalue", "size" => 30, "class" => "form-control", "id" => "fieldSvalue"]); ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
